- name: Installs java
  package:
    name: java-1.8.0-openjdk
    state: present

- name: Add the user 'minecraft' with group 'minecraft'
  user:
    name: minecraft
    group: minecraft
    comment: User to manage minecraft

- name: Create directory
  file:
    path: /dev/sdh/opt/minecraft
    state: directory
    owner: minecraft
    group: minecraft

- name: Create directory
  file:
    path: /dev/sdh/opt/minecraft/logs
    state: directory

- name: Download minecraft server
  get_url:
    url: https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar
    dest: /dev/sdh/opt/minecraft/bin/minecraft_server.jar

- name: Copy minecraft systemd service
  copy:
    src: "{{ playbook_dir }}/files/minecraft.service"
    dest: /etc/systemd/system
    owner: root
    group: root
